[package]
name = "pokesearch"
version = "0.1.0"
authors = ["rivera26 <rivera26@pdx.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
